### ISSUE TITLE
No such file or directory  TAU-urban-acoustic-scenes-2024-mobile-evaluation/meta.csv

### ISSUE THREAD

**Issue by chester-w-xie** [CPJKU/dcase2024_task1_baseline#5]
TAU-urban-acoustic-scenes-2022-mobile-development/../TAU-urban-acoustic-scenes-2024-mobile-evaluation/meta.csv'

there is no meta.csv in the evaluation dataset, but only /evaluation_setup/fold1_test.csv

**Comment by fschmid56** [comment]
Thanks for pointing this out! I updated the path.
